# cbindgen 0.29.2

pragma_once = true
include_version = true
namespaces = ["v5gdb", "impl"]
no_includes = true
sys_includes = ["cstddef", "cstdint"]
usize_is_size_t = true

[fn]
no_return = "[[noreturn]]"
