name: Rust

on: [push, pull_request, workflow_dispatch]

jobs:
    check:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Setup | Checkout
              uses: actions/checkout@v6

            - name: Setup | Toolchain
              run: rustup toolchain install --profile minimal

            - name: Setup | Build cache
              uses: Swatinem/rust-cache@v2
              with:
                workspaces: |
                  firmware
                  .

            - name: Setup | Install libudev
              run: sudo apt-get update && sudo apt-get install -y libudev-dev

            - name: Check (VEXos)
              run: cargo check --all-targets
              working-directory: firmware

            - name: Check (host tools)
              run: cargo check --all-targets
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Setup | Checkout
              uses: actions/checkout@v6

            - name: Setup | Toolchain
              run: rustup toolchain install --profile minimal

            - name: Setup | Install clippy
              run: rustup component add clippy

            - name: Setup | Build cache
              uses: Swatinem/rust-cache@v2
              with:
                workspaces: |
                  firmware
                  .

            - name: Setup | Install libudev
              run: sudo apt-get update && sudo apt-get install -y libudev-dev

            - name: Clippy (VEXos)
              run: cargo clippy --all-targets
              working-directory: firmware
              env:
                RUSTFLAGS: "-Dwarnings"

            - name: Clippy (host tools)
              run: cargo clippy --all-targets
              env:
                RUSTFLAGS: "-Dwarnings"
    fmt:
        name: Rustfmt
        runs-on: ubuntu-latest
        steps:
            - name: Setup | Checkout
              uses: actions/checkout@v6

            - name: Setup | Toolchain
              run: rustup toolchain install --profile minimal

            - name: Setup | Install Rustfmt
              run: rustup component add rustfmt

            - name: Check formatting
              run: |
                cargo fmt --all --check
                cd firmware && cargo fmt --all --check
